#!/bin/sh

set -e

TAG="$1"
shift

SENDMAIL="$GIT_REPLI_SENDMAIL"
[ "$SENDMAIL" = "" ] && { SENDMAIL=sendmail; }

git-repli-create-bundle

[ -e .git/git-repli-bundle ] || exit 0;

for TO in "$*"; do git-repli-format-mail $TAG $TO | $SENDMAIL $TO; done

git-repli-update-timestamp

