#!/bin/sh

MSG_DIR="$1"
TO_ADDR="$2"

set -e

[ -d .git ] || { echo 'execute me in root repository dir (where .git subdir is located)!' 1>&2; exit 1; }
[ "$TO_ADDR" != "" ] || { echo "you must specify recipient's email address!" 1>&2; exit 1; }

AUTHOR=$(git config user.email) || { echo 'use "git config user.email ..." to set your email!' 1>&2; exit 1; }
TAG=$(git-repli-get tag)

cat <<EOF
From: $AUTHOR
To: $TO_ADDR
Subject: [$TAG]

EOF

(cd $MSG_DIR; tar czf - *) | if [ "$(git-repli-get plain)" = "1" ]; then
    gpg --enarmour
else
    gpg --use-agent --armour --trust-model always -s -e -u $AUTHOR -r $TO_ADDR
fi
echo

rm $MSG_DIR/*; rmdir $MSG_DIR
