#!/bin/sh

set -e

[ -d .git ] || { echo 'execute me in root repository dir (where .git subdir is located)!' 1>&2; exit 1; }

TS=$(git config git-repli.bundletimestamp)

if [ "$1" != "" ]; then
	TS=$($1 $TS)
fi

echo $TS

git config --unset-all git-repli.lasttimestamp
git config --replace-all git-repli.lasttimestamp $TS
