#!/bin/sh

set -e

[ -d .git ] || { echo 'execute me in root repository dir (where .git subdir is located)!' 1>&2; exit 1; }

TS=$(git config git-repli.bundletimestamp)

[ "$1" != "" ] && {	TS=$1; }

git config --unset-all git-repli.lasttimestamp
git config --replace-all git-repli.lasttimestamp $TS
