#!/bin/sh

# requires: nmh

SRC_FOLDER="$1"
ARCHIVE_FOLDER="$2"
TAG="\\[$3\\]"
echo $0: $SRC_FOLDER $ARCHIVE_FOLDER $TAG 1>&2

msgs=$(pick $SRC_FOLDER -subject $TAG 2> /dev/null)
if [ "$msgs" != "0" ]; then
    show $SRC_FOLDER $msgs -noshowproc | egrep '^Subject: |From: |Date: ' 1>&2
    show $SRC_FOLDER $msgs -noshowproc
    folder +$ARCHIVE_FOLDER -create 1>&2
    refile $msgs -unlink -src $SRC_FOLDER $ARCHIVE_FOLDER 1>&2
    rmm +inbox $(pick +inbox -subject $TAG 2> /dev/null) -unlink 1>&2
fi
