#!/bin/sh

# requires: nmh

TAG="\\[$1\\]"
SRC_FOLDER="$2"
ARCHIVE_FOLDER="$3"

msgs=$(pick $SRC_FOLDER -subject $TAG 2> /dev/null)
if [ "$msgs" != "0" ]; then
	show $SRC_FOLDER $msgs -noshowproc | egrep '^Subject: |From: |Date: ' 1>&2
	show $SRC_FOLDER $msgs -noshowproc
	folder +$ARCHIVE_FOLDER -create 1>&2
	refile $msgs -unlink -src $SRC_FOLDER $ARCHIVE_FOLDER 1>&2
	rmm +inbox $(pick +inbox -subject $TAG 2> /dev/null) -unlink 1>&2
fi
