#!/bin/sh

# requires: getmail

TAG="$1"

cd `dirname $0`

touch new-mail
getmail -r getmailrc -q --new
cat new-mail >> all-mail
cat new-mail | awk "/^Subject: \[$TAG\]/ { a=1; } /^From / { a=0; } { if (a) print \$0; }"
rm new-mail
